    service: forland
    provider:
      name: aws
      region: eu-west-1
      runtime: nodejs6.10
      iamRoleStatements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmil
          Resource:
               - "*"
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
             Fn::Join:
               - ""
               - - "arn:aws:dynamodb:*:*:table/"
                 - Ref: ProductsDynamoDbTable
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
             Fn::Join:
               - ""
               - - "arn:aws:dynamodb:*:*:table/"
                 - Ref: GamesDynamoDbTable                 
 

    functions:
      getgames:
        handler: handler.getgames
        events:
          - http:
              path: games/{id}
              method: get
              cors: true
      getstats:
        handler: handler.getstats
        events:
          - http:
              path: stats/{id}
              method: get
              cors: true      
      getgameinfo:
        handler: handler.getgameinfo
        events:
          - http:
              path: gameinfo/{id}
              method: get
              cors: true    
      creategames:
        handler: handler.creategames
        events:
          - http:
              path: creategames
              method: post
              cors: true
      create:
        handler: handler.create
        events:
          - http:
              path: products
              method: post
              cors: true
      list:
        handler: handler.list
        events:
          - http:
              path: products
              method: get
              cors: true
      view:
        handler: handler.view
        events:
          - http:
              path: products/{id}
              method: get
              cors: true
      remove:
        handler: handler.remove
        events:
          - http:
              path: products/{id}
              method: delete
              cors: true

    resources:
      Resources:
        ProductsDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: products
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        GamesDynamoDbTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: games
            AttributeDefinitions:
              - AttributeName: forening
                AttributeType: S
              - AttributeName: hold
                AttributeType: S  
            KeySchema:
              - AttributeName: forening
                KeyType: HASH
              - AttributeName: hold
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5