    service: floorballStats
    provider:
      name: aws
      stage: prod
      region: eu-west-1
      runtime: nodejs6.10
      iamRoleStatements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmil
          Resource:
               - "*"
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:*:*:table/*"
              
    functions:
      updateEmailLeagues:
        handler: handler.updateEmailLeagues
        events:
          - http:
              path: updateEmailLeagues
              method: post
              cors: true 
      updateGames:
        handler: handler.updateGames
        events:
          - http:
              path: updateGames
              method: post
              cors: true 
      getLeagues:
        handler: handler.getLeagues
        events:
          - http:
              path: getLeagues/{season}
              method: get
              cors: true 
      updateLeagues:
        handler: handler.updateLeagues
        events:
          - http:
              path: updateLeagues
              method: post
              cors: true  
      getSignedLeaguesByEmailAddress:
        handler: handler.getSignedLeaguesByEmailAddress
        events:
          - http:
              path: getSignedLeaguesByEmailAddress
              method: post
              cors: true       
      sendSignedEmails:
        handler: handler.sendSignedEmails
        events:
          - http:
              path: sendSignedEmails
              method: get
              cors: true
      getgames:
        handler: handler.getgames
        events:
          - http:
              path: games/{id}
              method: get
              cors: true
      getstats:
        handler: handler.getstats
        events:
          - http:
              path: stats/{id}
              method: get
              cors: true      
      getgameinfo:
        handler: handler.getgameinfo
        events:
          - http:
              path: gameinfo/{id}
              method: get
              cors: true    

    resources:
      Resources:
        FloorballLeagues:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: leagues
            AttributeDefinitions:
              - AttributeName: leagueId
                AttributeType: S
              - AttributeName: leagueName
                AttributeType: S  
            KeySchema:
              - AttributeName: leagueId
                KeyType: HASH
              - AttributeName: leagueName
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        LeagueGames:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: leagueGames
            AttributeDefinitions:
              - AttributeName: leagueId
                AttributeType: S
              - AttributeName: leagueName
                AttributeType: S  
            KeySchema:
              - AttributeName: leagueId
                KeyType: HASH
              - AttributeName: leagueName
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        NewLeagueGames:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: newLeagueGames
            AttributeDefinitions:
              - AttributeName: leagueId
                AttributeType: S
              - AttributeName: gameId
                AttributeType: S  
            KeySchema:
              - AttributeName: leagueId
                KeyType: HASH
              - AttributeName: gameId
                KeyType: RANGE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5              
        SignedUpLeagues:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: signedUpLeagues
            AttributeDefinitions:
              - AttributeName: emailAddress
                AttributeType: S
            KeySchema:
              - AttributeName: emailAddress
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5